# Site settings
title: Umburanas
description: >- # this means to ignore newlines until "baseurl:"
  Documentação e evolução de um projeto agroflorestal sintrópico em Monte Branco.
  Compartilhando experiências, técnicas e aprendizados sobre sistemas agroflorestais
  sustentáveis na região da Caatinga.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://umburanas.github.io" # the base hostname & protocol for your site

# SEO settings
author: Projeto Umburanas
keywords: agrofloresta, sistema agroflorestal, sintropia, caatinga, sustentabilidade, permacultura
lang: pt-BR

# Internationalization
languages: ["pt", "es", "en", "de"]
default_lang: "pt"
exclude_from_localization: ["javascript", "images", "css", "figuras", "assets"]
parallel_localization: true

# Social media
github_username: umburanas

# Theme and plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - historia.md
  - evolucao.md
  - consorcios.md
  - recursos.md
  - sobre.md
  - contato.md

# Custom navigation titles (short versions for menu)
navigation:
  index.md: "Início"
  historia.md: "História"
  evolucao.md: "Evolução"
  consorcios.md: "Consórcios"
  recursos.md: "Recursos"
  sobre.md: "Sobre"
  contato.md: "Contato"

# Collections
collections:
  evolucao:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "evolucao"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - figuras_nao_usadas_ainda/
  - tabelas/venv/
  - tabelas/pdf/venv/
  - "**/*.pyc"
  - "**/__pycache__/"

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
