name: PR Preview
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # build your site here if needed (npm run build / jekyll build, etc.)
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .          # or your built output dir
          preview-branch: gh-pages

