name: PR Preview
on:
  pull_request: { types: [opened, synchronize, reopened, closed] }
permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write
jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-version: 'latest'
          bundler-cache: true
      - name: Build Jekyll
        if: github.event.action != 'closed'
        run: |
          bundle install
          bundle exec jekyll build
      - name: Deploy PR preview
        if: github.event.action != 'closed'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site
          # this should match the branch your Pages site deploys from
          preview-branch: gh-pages
      - name: Remove preview on close
        if: github.event.action == 'closed'
        uses: rossjrw/pr-preview-action@v1
        with:
          action: remove
          preview-branch: gh-pages
